#!/bin/bash

#SBATCH --account=jonmay_231
#SBATCH --partition=gpu
#SBATCH --gpus-per-task=2
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=32
#SBATCH --mem=80G
#SBATCH --time=12:00:00

module purge
# module load gcc/11.3.0
# module load python/3.11.3

#conda init
source ~/.bashrc
conda activate torch_env
#google/t5-base-lm-adapt 
#google/t5-xl-lm-adapt

 

PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:128 torchrun train_new_base.py

conda deactivate